// Compiler/Interpreter 

// Auto-generated enumerations for command table (from AGK API)
#include "AGKCommandsTable106.h"
#include "AGKCommandsTable107.h"
#include "AGKCommandsTable107internal.h"
#include "AGKCommandsTable108.h"

// parameter enums (only used by compiler process)
// Java hates enums and makes a mockery of the ordinal performance feature
// AGKParamTypes:
#define AGKP_VARIABLE_NONE 0
#define AGKP_VARIABLE_INTEGER 1
#define AGKP_VARIABLE_FLOAT 2
#define AGKP_VARIABLE_STRING 3
#define AGKP_VARIABLE_DWORD 4
#define AGKP_VARIABLE_RES1 5
#define AGKP_VARIABLE_RES2 6
#define AGKP_VARIABLE_RES3 7
#define AGKP_VARIABLE_RES4 8
#define AGKP_VARIABLE_RES5 9
#define AGKP_VALUE_NONE 10
#define AGKP_VALUE_INTEGER 11
#define AGKP_VALUE_FLOAT 12
#define AGKP_VALUE_STRING 13
#define AGKP_VALUE_DWORD 14
#define AGKP_VALUE_RES1 15
#define AGKP_VALUE_RES2 16
#define AGKP_VALUE_RES3 17
#define AGKP_VALUE_RES4 18
#define AGKP_VALUE_RES5 19
#define AGKP_OFFSET_NONE 20
#define AGKP_OFFSET_INTEGER 21
#define AGKP_OFFSET_FLOAT 22
#define AGKP_OFFSET_STRING 23
#define AGKP_OFFSET_DWORD 24
#define AGKP_OFFSET_RES1 25
#define AGKP_OFFSET_RES2 26
#define AGKP_OFFSET_RES3 27
#define AGKP_OFFSET_RES4 28
#define AGKP_OFFSET_RES5 29
#define AGKP_ARRAY_NONE 30
#define AGKP_ARRAY_INTEGER 31
#define AGKP_ARRAY_FLOAT 32
#define AGKP_ARRAY_STRING 33
#define AGKP_ARRAY_DWORD 34
#define AGKP_ARRAY_RES1 35
#define AGKP_ARRAY_RES2 36
#define AGKP_ARRAY_RES3 37
#define AGKP_ARRAY_RES4 38
#define AGKP_ARRAY_RES5 39
#define AGKP_USERDATATYPE 40
#define AGKP_USERDATATYPE_ARRAY 41
#define AGKP_USERDATATYPEPTR 42
#define AGKP_SIZE_USERFUNCTION 43
#define AGKP_LABEL 44
#define AGKP_USERDATATYPE_OFFSET 45
/*
enum AGKParamTypes	{	
		AGKP_VARIABLE_NONE,
		AGKP_VARIABLE_INTEGER,
		AGKP_VARIABLE_FLOAT,
		AGKP_VARIABLE_STRING,
		AGKP_VARIABLE_DWORD,
		AGKP_VARIABLE_RES1,
		AGKP_VARIABLE_RES2,
		AGKP_VARIABLE_RES3,
		AGKP_VARIABLE_RES4,
		AGKP_VARIABLE_RES5,
		AGKP_VALUE_NONE,
		AGKP_VALUE_INTEGER,
		AGKP_VALUE_FLOAT,
		AGKP_VALUE_STRING,
		AGKP_VALUE_DWORD,
		AGKP_VALUE_RES1,
		AGKP_VALUE_RES2,
		AGKP_VALUE_RES3,
		AGKP_VALUE_RES4,
		AGKP_VALUE_RES5,
		AGKP_OFFSET_NONE,
		AGKP_OFFSET_INTEGER,
		AGKP_OFFSET_FLOAT,
		AGKP_OFFSET_STRING,
		AGKP_OFFSET_DWORD,
		AGKP_OFFSET_RES1,
		AGKP_OFFSET_RES2,
		AGKP_OFFSET_RES3,
		AGKP_OFFSET_RES4,
		AGKP_OFFSET_RES5,
		AGKP_ARRAY_NONE,
		AGKP_ARRAY_INTEGER,
		AGKP_ARRAY_FLOAT,
		AGKP_ARRAY_STRING,
		AGKP_ARRAY_DWORD,
		AGKP_ARRAY_RES1,
		AGKP_ARRAY_RES2,
		AGKP_ARRAY_RES3,
		AGKP_ARRAY_RES4,
		AGKP_ARRAY_RES5,
		AGKP_USERDATATYPE,
		AGKP_USERDATATYPE_ARRAY,
		AGKP_USERDATATYPEPTR,
		AGKP_SIZE_USERFUNCTION,
		AGKP_LABEL,
		AGKP_USERDATATYPE_OFFSET
};
*/

// structures (22 = 10 params + 1 returnparam + shadow indices for array subscript params 11-21)
struct sByteCode
{
	DWORD dwLineNumber;
	DWORD dwInstruction;
	DWORD dwParamCount;
	BYTE cPType[22];
	DWORD dwPOffset[22];
	DWORD dwPSize[22];
	union
	{
		int iP[22];
		float fP[22];
		LPSTR pP[22];
		DWORD dwP[22];
	};
};

// command enums
enum AGKInstructions {	

		// 090911 - add five dummy instructions in free byte code
		// meaning all byte code instructions are shifted making the
		// byte code from free versions completely incompatible with 
		// full version builds (which do not have these five dummy IDs)
		//#ifdef JAVAWILLOMIT
		#ifdef FREEVERSION
				AGKI_FREEVERSION_DUMMY1,
				AGKI_FREEVERSION_DUMMY2,
				AGKI_FREEVERSION_DUMMY3,
				AGKI_FREEVERSION_DUMMY4,
				AGKI_FREEVERSION_DUMMY5,
		#endif
		//#endif

		AGKI_NOP,
		AGKI_INCVAR_NOP,
		AGKI_INCVAR_VARIABLE_INTEGER,
		AGKI_INCVAR_VARIABLE_INTEGER_VARIABLE_INTEGER,
		AGKI_INCVAR_VARIABLE_INTEGER_VARIABLE_FLOAT,
		AGKI_INCVAR_VARIABLE_INTEGER_VARIABLE_DWORD,
		AGKI_INCVAR_VARIABLE_INTEGER_VALUE_INTEGER,
		AGKI_INCVAR_VARIABLE_INTEGER_VALUE_FLOAT,
		AGKI_INCVAR_VARIABLE_INTEGER_VALUE_DWORD,
		AGKI_INCVAR_VARIABLE_FLOAT,
		AGKI_INCVAR_VARIABLE_FLOAT_VARIABLE_INTEGER,
		AGKI_INCVAR_VARIABLE_FLOAT_VARIABLE_FLOAT,
		AGKI_INCVAR_VARIABLE_FLOAT_VARIABLE_DWORD,
		AGKI_INCVAR_VARIABLE_FLOAT_VALUE_INTEGER,
		AGKI_INCVAR_VARIABLE_FLOAT_VALUE_FLOAT,
		AGKI_INCVAR_VARIABLE_FLOAT_VALUE_DWORD,
		AGKI_INCVAR_VARIABLE_DWORD,
		AGKI_INCVAR_VARIABLE_DWORD_VARIABLE_INTEGER,
		AGKI_INCVAR_VARIABLE_DWORD_VARIABLE_FLOAT,
		AGKI_INCVAR_VARIABLE_DWORD_VARIABLE_DWORD,
		AGKI_INCVAR_VARIABLE_DWORD_VALUE_INTEGER,
		AGKI_INCVAR_VARIABLE_DWORD_VALUE_FLOAT,
		AGKI_INCVAR_VARIABLE_DWORD_VALUE_DWORD,

		AGKI_DECVAR_NOP,
		AGKI_DECVAR_VARIABLE_INTEGER,
		AGKI_DECVAR_VARIABLE_INTEGER_VARIABLE_INTEGER,
		AGKI_DECVAR_VARIABLE_INTEGER_VARIABLE_FLOAT,
		AGKI_DECVAR_VARIABLE_INTEGER_VARIABLE_DWORD,
		AGKI_DECVAR_VARIABLE_INTEGER_VALUE_INTEGER,
		AGKI_DECVAR_VARIABLE_INTEGER_VALUE_FLOAT,
		AGKI_DECVAR_VARIABLE_INTEGER_VALUE_DWORD,
		AGKI_DECVAR_VARIABLE_FLOAT,
		AGKI_DECVAR_VARIABLE_FLOAT_VARIABLE_INTEGER,
		AGKI_DECVAR_VARIABLE_FLOAT_VARIABLE_FLOAT,
		AGKI_DECVAR_VARIABLE_FLOAT_VARIABLE_DWORD,
		AGKI_DECVAR_VARIABLE_FLOAT_VALUE_INTEGER,
		AGKI_DECVAR_VARIABLE_FLOAT_VALUE_FLOAT,
		AGKI_DECVAR_VARIABLE_FLOAT_VALUE_DWORD,
		AGKI_DECVAR_VARIABLE_DWORD,
		AGKI_DECVAR_VARIABLE_DWORD_VARIABLE_INTEGER,
		AGKI_DECVAR_VARIABLE_DWORD_VARIABLE_FLOAT,
		AGKI_DECVAR_VARIABLE_DWORD_VARIABLE_DWORD,
		AGKI_DECVAR_VARIABLE_DWORD_VALUE_INTEGER,
		AGKI_DECVAR_VARIABLE_DWORD_VALUE_FLOAT,
		AGKI_DECVAR_VARIABLE_DWORD_VALUE_DWORD,

		AGKI_MATH_MUL,
		AGKI_MATH_DIV,
		AGKI_MATH_ADD,
		AGKI_MATH_SUB,
		AGKI_MATH_MOD,
		AGKI_MATH_SHR,
		AGKI_MATH_SHL,
		AGKI_MATH_OR,
		AGKI_MATH_XOR,
		AGKI_MATH_BITNOT,
		AGKI_MATH_AND,
		AGKI_MATH_NOT,
		AGKI_MATH_EQUAL,
		AGKI_MATH_NOTEQUAL,
		AGKI_MATH_GREATER,
		AGKI_MATH_GREATEREQUAL,
		AGKI_MATH_LESS,
		AGKI_MATH_LESSEQUAL,

		AGKI_EQUALLFF_VARIABLE_INTEGER_VARIABLE_FLOAT_VARIABLE_FLOAT,
		AGKI_NOTEQUALLFF_VARIABLE_INTEGER_VARIABLE_FLOAT_VARIABLE_FLOAT,
		AGKI_GREATERLFF_VARIABLE_INTEGER_VARIABLE_FLOAT_VARIABLE_FLOAT,
		AGKI_GREATEREQUALLFF_VARIABLE_INTEGER_VARIABLE_FLOAT_VARIABLE_FLOAT,
		AGKI_LESSLFF_VARIABLE_INTEGER_VARIABLE_FLOAT_VARIABLE_FLOAT,
		AGKI_LESSEQUALLFF_VARIABLE_INTEGER_VARIABLE_FLOAT_VARIABLE_FLOAT,
		AGKI_EQUALLSS_VARIABLE_INTEGER_VARIABLE_STRING_VARIABLE_STRING,
		AGKI_NOTEQUALLSS_VARIABLE_INTEGER_VARIABLE_STRING_VARIABLE_STRING,
		AGKI_GREATERLSS_VARIABLE_INTEGER_VARIABLE_STRING_VARIABLE_STRING,
		AGKI_GREATEREQUALLSS_VARIABLE_INTEGER_VARIABLE_STRING_VARIABLE_STRING,
		AGKI_LESSLSS_VARIABLE_INTEGER_VARIABLE_STRING_VARIABLE_STRING,
		AGKI_LESSEQUALLSS_VARIABLE_INTEGER_VARIABLE_STRING_VARIABLE_STRING,
		AGKI_EQUALLSS_VARIABLE_INTEGER_VALUE_STRING_VALUE_STRING,
		AGKI_NOTEQUALLSS_VARIABLE_INTEGER_VALUE_STRING_VALUE_STRING,
		AGKI_GREATERLSS_VARIABLE_INTEGER_VALUE_STRING_VALUE_STRING,
		AGKI_GREATEREQUALLSS_VARIABLE_INTEGER_VALUE_STRING_VALUE_STRING,
		AGKI_LESSLSS_VARIABLE_INTEGER_VALUE_STRING_VALUE_STRING,
		AGKI_LESSEQUALLSS_VARIABLE_INTEGER_VALUE_STRING_VALUE_STRING,

		AGKI_MULFFF_VARIABLE_FLOAT_VALUE_FLOAT,
		AGKI_DIVFFF_VARIABLE_FLOAT_VALUE_FLOAT,
		AGKI_ADDFFF_VARIABLE_FLOAT_VALUE_FLOAT,
		AGKI_SUBFFF_VARIABLE_FLOAT_VALUE_FLOAT,

		AGKI_ADDSSS_VARIABLE_STRING_VARIABLE_STRING_VARIABLE_STRING,

		AGKI_POWERLLL_VARIABLE_INTEGER_VARIABLE_INTEGER_VARIABLE_INTEGER,
		AGKI_POWERFFF_VARIABLE_FLOAT_VARIABLE_FLOAT_VARIABLE_FLOAT,
		AGKI_POWERDDD_VARIABLE_DWORD_VARIABLE_DWORD_VARIABLE_DWORD,
	
		AGKI_ASSIGNRETURNVAR,
		AGKI_ASSIGNRETURNUDT,
		AGKI_ASSIGNVAR_NOP,
		AGKI_ASSIGNVAR_VARIABLE_INTEGER_VARIABLE_INTEGER,
		AGKI_ASSIGNVAR_VARIABLE_INTEGER_VALUE_INTEGER,
		AGKI_ASSIGNVAR_VARIABLE_INTEGER_OFFSET_INTEGER,
		AGKI_ASSIGNVAR_VARIABLE_INTEGER_ARRAY_INTEGER,
		AGKI_ASSIGNVAR_VARIABLE_FLOAT_VARIABLE_FLOAT,
		AGKI_ASSIGNVAR_VARIABLE_FLOAT_VALUE_FLOAT,
		AGKI_ASSIGNVAR_VARIABLE_FLOAT_OFFSET_FLOAT,
		AGKI_ASSIGNVAR_VARIABLE_FLOAT_ARRAY_FLOAT,
		AGKI_ASSIGNVAR_VARIABLE_DWORD_VARIABLE_DWORD,
		AGKI_ASSIGNVAR_VARIABLE_DWORD_VALUE_DWORD,
		AGKI_ASSIGNVAR_VARIABLE_DWORD_OFFSET_DWORD,
		AGKI_ASSIGNVAR_VARIABLE_DWORD_ARRAY_DWORD,
		AGKI_ASSIGNVAR_OFFSET_INTEGER_VARIABLE_INTEGER,
		AGKI_ASSIGNVAR_OFFSET_INTEGER_VALUE_INTEGER,
		AGKI_ASSIGNVAR_OFFSET_INTEGER_OFFSET_INTEGER,
		AGKI_ASSIGNVAR_OFFSET_INTEGER_ARRAY_INTEGER,
		AGKI_ASSIGNVAR_OFFSET_FLOAT_VARIABLE_FLOAT,
		AGKI_ASSIGNVAR_OFFSET_FLOAT_VALUE_FLOAT,
		AGKI_ASSIGNVAR_OFFSET_FLOAT_OFFSET_FLOAT,
		AGKI_ASSIGNVAR_OFFSET_FLOAT_ARRAY_FLOAT,
		AGKI_ASSIGNVAR_OFFSET_DWORD_VARIABLE_DWORD,
		AGKI_ASSIGNVAR_OFFSET_DWORD_VALUE_DWORD,
		AGKI_ASSIGNVAR_OFFSET_DWORD_OFFSET_DWORD,
		AGKI_ASSIGNVAR_OFFSET_DWORD_ARRAY_DWORD,
		AGKI_ASSIGNVAR_ARRAY_INTEGER_VARIABLE_INTEGER,
		AGKI_ASSIGNVAR_ARRAY_INTEGER_VALUE_INTEGER,
		AGKI_ASSIGNVAR_ARRAY_INTEGER_OFFSET_INTEGER,
		AGKI_ASSIGNVAR_ARRAY_INTEGER_ARRAY_INTEGER,
		AGKI_ASSIGNVAR_ARRAY_FLOAT_VARIABLE_FLOAT,
		AGKI_ASSIGNVAR_ARRAY_FLOAT_VALUE_FLOAT,
		AGKI_ASSIGNVAR_ARRAY_FLOAT_OFFSET_FLOAT,
		AGKI_ASSIGNVAR_ARRAY_FLOAT_ARRAY_FLOAT,
		AGKI_ASSIGNVAR_ARRAY_STRING_VARIABLE_STRING,
		AGKI_ASSIGNVAR_ARRAY_STRING_VALUE_STRING,
		AGKI_ASSIGNVAR_ARRAY_STRING_OFFSET_STRING,
		AGKI_ASSIGNVAR_ARRAY_STRING_ARRAY_STRING,
		AGKI_ASSIGNVAR_ARRAY_DWORD_VARIABLE_DWORD,
		AGKI_ASSIGNVAR_ARRAY_DWORD_VALUE_DWORD,
		AGKI_ASSIGNVAR_ARRAY_DWORD_OFFSET_DWORD,
		AGKI_ASSIGNVAR_ARRAY_DWORD_ARRAY_DWORD,
		AGKI_ASSIGNVAR_USERDATATYPE_USERDATATYPE,
		AGKI_COPYBYTEMEMORY_VALUE_DWORD_USERDATATYPE_USERDATATYPE,

		AGKI_ARRAY_CALC_OFFSET,

		AGKI_JUMPIFTRUE,
		AGKI_JUMPIFFALSE,

		AGKI_CASTLTOD_NOP,
		AGKI_CASTLTOD_VARIABLE_DWORD_VARIABLE_INTEGER,
		AGKI_CASTLTOD_VARIABLE_DWORD_VALUE_INTEGER,
		AGKI_CASTLTOD_VARIABLE_DWORD_OFFSET_INTEGER,
		AGKI_CASTLTOD_VARIABLE_DWORD_ARRAY_INTEGER,
		AGKI_CASTLTOD_OFFSET_DWORD_VARIABLE_INTEGER,
		AGKI_CASTLTOD_OFFSET_DWORD_VALUE_INTEGER,
		AGKI_CASTLTOD_OFFSET_DWORD_OFFSET_INTEGER,
		AGKI_CASTLTOD_OFFSET_DWORD_ARRAY_INTEGER,
		AGKI_CASTLTOD_ARRAY_DWORD_VARIABLE_INTEGER,
		AGKI_CASTLTOD_ARRAY_DWORD_VALUE_INTEGER,
		AGKI_CASTLTOD_ARRAY_DWORD_OFFSET_INTEGER,
		AGKI_CASTLTOD_ARRAY_DWORD_ARRAY_INTEGER,

		AGKI_CASTLTOF_NOP,
		AGKI_CASTLTOF_VARIABLE_FLOAT_VARIABLE_INTEGER,
		AGKI_CASTLTOF_VARIABLE_FLOAT_VALUE_INTEGER,
		AGKI_CASTLTOF_VARIABLE_FLOAT_OFFSET_INTEGER,
		AGKI_CASTLTOF_VARIABLE_FLOAT_ARRAY_INTEGER,
		AGKI_CASTLTOF_OFFSET_FLOAT_VARIABLE_INTEGER,
		AGKI_CASTLTOF_OFFSET_FLOAT_VALUE_INTEGER,
		AGKI_CASTLTOF_OFFSET_FLOAT_OFFSET_INTEGER,
		AGKI_CASTLTOF_OFFSET_FLOAT_ARRAY_INTEGER,
		AGKI_CASTLTOF_ARRAY_FLOAT_VARIABLE_INTEGER,
		AGKI_CASTLTOF_ARRAY_FLOAT_VALUE_INTEGER,
		AGKI_CASTLTOF_ARRAY_FLOAT_OFFSET_INTEGER,
		AGKI_CASTLTOF_ARRAY_FLOAT_ARRAY_INTEGER,

		AGKI_CASTFTOL_NOP,
		AGKI_CASTFTOL_VARIABLE_INTEGER_VARIABLE_FLOAT,
		AGKI_CASTFTOL_VARIABLE_INTEGER_VALUE_FLOAT,
		AGKI_CASTFTOL_VARIABLE_INTEGER_OFFSET_FLOAT,
		AGKI_CASTFTOL_VARIABLE_INTEGER_ARRAY_FLOAT,
		AGKI_CASTFTOL_OFFSET_INTEGER_VARIABLE_FLOAT,
		AGKI_CASTFTOL_OFFSET_INTEGER_VALUE_FLOAT,
		AGKI_CASTFTOL_OFFSET_INTEGER_OFFSET_FLOAT,
		AGKI_CASTFTOL_OFFSET_INTEGER_ARRAY_FLOAT,
		AGKI_CASTFTOL_ARRAY_INTEGER_VARIABLE_FLOAT,
		AGKI_CASTFTOL_ARRAY_INTEGER_VALUE_FLOAT,
		AGKI_CASTFTOL_ARRAY_INTEGER_OFFSET_FLOAT,
		AGKI_CASTFTOL_ARRAY_INTEGER_ARRAY_FLOAT,

		AGKI_CASTFTOD_NOP,
		AGKI_CASTFTOD_VARIABLE_DWORD_VARIABLE_FLOAT,
		AGKI_CASTFTOD_VARIABLE_DWORD_VALUE_FLOAT,
		AGKI_CASTFTOD_VARIABLE_DWORD_OFFSET_FLOAT,
		AGKI_CASTFTOD_VARIABLE_DWORD_ARRAY_FLOAT,
		AGKI_CASTFTOD_OFFSET_DWORD_VARIABLE_FLOAT,
		AGKI_CASTFTOD_OFFSET_DWORD_VALUE_FLOAT,
		AGKI_CASTFTOD_OFFSET_DWORD_OFFSET_FLOAT,
		AGKI_CASTFTOD_OFFSET_DWORD_ARRAY_FLOAT,
		AGKI_CASTFTOD_ARRAY_DWORD_VARIABLE_FLOAT,
		AGKI_CASTFTOD_ARRAY_DWORD_VALUE_FLOAT,
		AGKI_CASTFTOD_ARRAY_DWORD_OFFSET_FLOAT,
		AGKI_CASTFTOD_ARRAY_DWORD_ARRAY_FLOAT,

		AGKI_CASTDTOL_NOP,
		AGKI_CASTDTOL_VARIABLE_INTEGER_VARIABLE_DWORD,
		AGKI_CASTDTOL_VARIABLE_INTEGER_VALUE_DWORD,
		AGKI_CASTDTOL_VARIABLE_INTEGER_OFFSET_DWORD,
		AGKI_CASTDTOL_VARIABLE_INTEGER_ARRAY_DWORD,
		AGKI_CASTDTOL_OFFSET_INTEGER_VARIABLE_DWORD,
		AGKI_CASTDTOL_OFFSET_INTEGER_VALUE_DWORD,
		AGKI_CASTDTOL_OFFSET_INTEGER_OFFSET_DWORD,
		AGKI_CASTDTOL_OFFSET_INTEGER_ARRAY_DWORD,
		AGKI_CASTDTOL_ARRAY_INTEGER_VARIABLE_DWORD,
		AGKI_CASTDTOL_ARRAY_INTEGER_VALUE_DWORD,
		AGKI_CASTDTOL_ARRAY_INTEGER_OFFSET_DWORD,
		AGKI_CASTDTOL_ARRAY_INTEGER_ARRAY_DWORD,

		AGKI_CASTDTOF_NOP,
		AGKI_CASTDTOF_VARIABLE_FLOAT_VARIABLE_DWORD,
		AGKI_CASTDTOF_VARIABLE_FLOAT_VALUE_DWORD,
		AGKI_CASTDTOF_VARIABLE_FLOAT_OFFSET_DWORD,
		AGKI_CASTDTOF_VARIABLE_FLOAT_ARRAY_DWORD,
		AGKI_CASTDTOF_OFFSET_FLOAT_VARIABLE_DWORD,
		AGKI_CASTDTOF_OFFSET_FLOAT_VALUE_DWORD,
		AGKI_CASTDTOF_OFFSET_FLOAT_OFFSET_DWORD,
		AGKI_CASTDTOF_OFFSET_FLOAT_ARRAY_DWORD,
		AGKI_CASTDTOF_ARRAY_FLOAT_VARIABLE_DWORD,
		AGKI_CASTDTOF_ARRAY_FLOAT_VALUE_DWORD,
		AGKI_CASTDTOF_ARRAY_FLOAT_OFFSET_DWORD,
		AGKI_CASTDTOF_ARRAY_FLOAT_ARRAY_DWORD,

		AGKI_EQUATESS_VARIABLE_STRING_VARIABLE_STRING,
		AGKI_EQUATESS_VARIABLE_STRING_VALUE_STRING,
		AGKI_FREESS_VARIABLE_STRING,
		AGKI_DIRECTJUMP,
		AGKI_PUSHSTACK,
		AGKI_PULLSTACK,
		AGKI_DIRECTJUMPSUBROUTINE,
		AGKI_DIRECTJUMPUSERFUNCTION,
		AGKI_RETURNFROMSUBROUTINE,
		AGKI_EARLYEND,
		AGKI_QUIT,
		AGKI_DIMDDD_VARIABLE_DWORD_VARIABLE_DWORD_VARIABLE_DWORD_VARIABLE_DWORD_VARIABLE_DWORD_VARIABLE_DWORD_VARIABLE_DWORD_VARIABLE_DWORD_VARIABLE_DWORD_VARIABLE_DWORD_VARIABLE_DWORD,
		AGKI_SYNCREAL,

		// In order to remain forward and backward compatibility with an older/newer Compiler/Player
		// the byte code instruction enmerations remain unaffected. New commands are ADDED to the end
		// of the list of enumerated commands (106->106/107 okay, 107->106/107 okay, e.t.c)

		// 100-106 build - original command set
		ALL_AGK_COMMANDS_106_DEFINE,

		// 107 build - advert, http, missing get files, missing key commands
		ALL_AGK_COMMANDS_107_DEFINE,
		ALL_AGK_COMMANDS_INTERNAL_DEFINE,

		// 108 build - 3D, social, Ultrabook commands
		ALL_AGK_COMMANDS_DEFINE,

		AGKI_LASTCOMMAND
};
